"""add soft delete fields

Revision ID: 2510929c5aac
Revises: ed97f06fceb3
Create Date: 2026-04-05 16:04:08.016033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2510929c5aac'
down_revision: Union[str, Sequence[str], None] = 'ed97f06fceb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_records', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('financial_records', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_records', 'deleted_at')
    op.drop_column('financial_records', 'is_deleted')
    # ### end Alembic commands ###
